"""adjust

Revision ID: 5ee1415e1bc0
Revises: 4f68f83c5040
Create Date: 2025-05-26 19:35:38.095422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee1415e1bc0'
down_revision = '4f68f83c5040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('productSizes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productSizes', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
